name: reformat-java
on: push

jobs:
  replace-google-format:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - uses: actions/checkout@v3
      - uses: axel-op/googlejavaformat-action@v3
        with:
          commit-message: 'style : Google Java Format ${{ github.head_ref }}'
          args: '--replace --aosp'
